name: gdpr-rag
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip=24.2
  - setuptools
  - wheel
  - tqdm
  - numpy=1.26
  - pandas=2.2
  - pyyaml
  - uvicorn=0.30
  - fastapi=0.115
  - requests=2.32
  - httpx=0.27
  - rich=13.7
  - pip:
      - chromadb==0.4.24
      - langchain==0.1.16
      - langchain-community==0.0.34
      - langchain-chroma==0.1.1
      - sentence-transformers==2.5.1
      - typer==0.12.3
      - python-dotenv==1.0.1
      - tenacity==8.2.3
      - duckdb==1.0.0
      - pyarrow==15.0.2
